[package]
name = "lingua"
version = "0.2.0"
edition = "2021"
authors = ["ShallmentMo <shallmentmo@gmail.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.8.2" }
lingua = "1.6.2"
